# We store the info as follows . For each room (key), we get a dict, with keys/values
# ROOMPASS: refers to which password the room should unlock (if none = 0)
# DOORPASS: dict with keys being door number (numbering goes for top left corner, left to right and then down)
# CLUE: string

DEFAULT_INFO = {'ROOMPASS': 0,
                'DOORPASS': {},
                'CLUE': '',
                }

ROOM_INFO = {1: {'ROOMPASS': 0,
                 'DOORPASS': {},
                 'CLUE': 'Il vous manque une case',
                 },
             2: {'ROOMPASS': 17,
                 'DOORPASS': {1: 1},
                 'CLUE': 'Vous devriez utiliser vosdoigts',
                 },
             3: {'ROOMPASS': 10,
                 'DOORPASS': {},
                 'CLUE': 'Un peu de perspective',
                 },
             4: {'ROOMPASS': 6,
                 'DOORPASS': {},
                 'CLUE': 'Il suffirait de peu pour etre juste',
                 },
             5: {'ROOMPASS': 7,
                 'DOORPASS': {2: 17},
                 'CLUE': 'Transcendance',
                 },
             6: {'ROOMPASS': 0,
                 'DOORPASS': {},
                 'CLUE': 'Il vous manque une case',
                 },
             7: {'ROOMPASS': 11,
                 'DOORPASS': {},
                 'CLUE': 'Soyons clair et mettons  les points sur les i',
                 },
             8: {'ROOMPASS': 13,
                 'DOORPASS': {1: 7},
                 'CLUE': 'Le temps est ecoule',
                 },
             9: {'ROOMPASS': 5,
                 'DOORPASS': {},
                 'CLUE': 'Content Pas Content',
                 },
             10: {'ROOMPASS': 0,
                  'DOORPASS': {},
                  'CLUE': 'Vous ne devriez pas etre ici',
                  },
             11: {'ROOMPASS': 8,
                  'DOORPASS': {},
                  'CLUE': 'Pauvre Blinky',
                  },
             12: {'ROOMPASS': 3,
                  'DOORPASS': {},
                  'CLUE': 'Par ici la sortie',
                  },
             13: {'ROOMPASS': 23,
                  'DOORPASS': {},
                  'CLUE': 'Kori o tokasu',
                  },
             14: {'ROOMPASS': 15,
                  'DOORPASS': {},
                  'CLUE': 'Retour a la racine',
                  },
             15: {'ROOMPASS': 0,
                  'DOORPASS': {},
                  'CLUE': 'A l\'identique.           Mais surtout a gauche',
                  },
             16: {'ROOMPASS': 9,
                  'DOORPASS': {},
                  'CLUE': 'Dans la continuite',
                  },

             19: {'ROOMPASS': 22,
                  'DOORPASS': {},
                  'CLUE': 'America !',
                  },

             20: {'ROOMPASS': 16,
                  'DOORPASS': {2: 23},
                  'CLUE': 'Transcendance',
                  },

             26: {'ROOMPASS': 0,
                  'DOORPASS': {},
                  'CLUE': 'This is the end',
                  },

             32: {'ROOMPASS': 0,
                  'DOORPASS': {2: 5},
                  'CLUE': 'Il vous manque une case',
                  },

             36: {'ROOMPASS': 26,
                  'DOORPASS': {},
                  'CLUE': 'Gliders... Game of Life',
                  },

             }
